### ISSUE TITLE
Flickering on ESP32 -> update MatrixGFXDemo

### ISSUE THREAD

**Issue by BatsIhor** [aligator/NeoPixelBusGfx#1]
Hey there, 

Just installed it on esp32 with 16x16 matrix and it has a lot of artifacts.
Howdy test is printed correctly but MatrixGFXDemo is a mess.

I'm not sure what the reason is but might be problem in Adafruit libraries. 

Thanks
Ihor

**Comment by aligator** [comment]
Thanks for the report, I didn't test it with an esp32 yet.
But the MatrixGFXDemo is actually not yet adapted to use this lib, (as I noted at the top of MatrixGFXDemo.ino), because I was too lazy...

So if the Howdy test works, everything should be fine.
I think I will adapt the MatrixGFXDemo soon when I have time and leave this issue open for this.

**Comment by aligator** [comment]
I just updated the demo:
https://github.com/aligator/NeoPixelBusGfx/commit/6c1a147f1b7ebc8efb856c7c28e70758b99d697d

But I tested it only with a ESP8266. So could you please test it with your ESP32 also?

**Comment by BatsIhor** [comment]
Thank you, I'm going to test it later today.

**Comment by BatsIhor** [comment]
I confirm it works! I'm not sure how do you you update it in a PlatformIO library list but I think you should push new release so people can start using it.
Thank you very much!

**Comment by aligator** [comment]
yeah, will do this tomorrow :-)

Thank you, too.

**Comment by aligator** [comment]
Should be published now.

**Comment by BatsIhor** [comment]
Just tested showing scrolling text and all works well up to the point when you use wifi, as soon as you use wifi you have random pixels light up with random colors. This issue is not new to ESP32 + WS2812b and it flickers on FastLED and NeoPixel libraries as well, no one seem to be able to fix that yet, so just want to leave this in here for someone who stuck on this and looking for a solution the way I did.
